PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX mei: <http://www.music-encoding.org/ns/mei#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?file
WHERE {
	VALUES (?location) { ("datasets/" ) }
	BIND (IRI(CONCAT("x-sparql-anything:","location=", ?location )) AS ?fx) .
	SERVICE ?fx {
		fx:properties fx:archive.matches ".*\\.json"
		.
		[] fx:anySlot ?file
		#[] xyz:lyrics ?lyrics
	}
}